name: 'Build love'
description: 'Build love file.'

inputs:
  filePath:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        7z a -tzip ${{ inputs.filePath }} media parts Zframework conf.lua main.lua version.lua
