name: 'Build love'
description: 'Build love file.'

inputs:
  filePath:
    required: true

runs:
  using: "composite"
  steps:
    - name: Pack Quatrack
      shell: bash
      run: |
        7z a -tzip ${{ inputs.filePath }} assets Zenitha conf.lua main.lua version.lua
