name: 'Build Android'
description: 'Build Android package.'

inputs:
  apkCode:
    required: true
  versionName:
    required: true
  versionCode:
    required: true
  commit:
    required: true
  filePath:
    required: true
  SIGNING_KEY:
    required: true
  KEY_STORE_PASSWORD:
    required: true
  ALIAS:
    required: true
  KEY_PASSWORD:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Clone love-android
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/26F-Studio/love-android -b CI --depth 1 --shallow-submodules
    - name: Get love pack
      uses: actions/download-artifact@v2
      with:
        name: Quatrack_${{ inputs.versionName }}_${{ GITHUB.RUN_NUMBER }}_${{ inputs.commit }}_Love
        path: love-android/app/src/main/assets
    - name: Update Android information
      shell: python
      run: |
        if '${{ GITHUB.REF_TYPE }}' == 'tag':
          appName = 'Quatrack'
          packageName = 'org.love2d.MrZ.Quatrack'
          edition = 'quatrack_release'
        elif '${{ GITHUB.REF_TYPE }}' == 'branch':
          appName = 'Quatrack_Snapshot'
          packageName = 'org.love2d.MrZ.Quatrack.Snapshot'
          edition = 'quatrack_snapshot'
        with open('./love-android/app/src/main/AndroidManifest.xml', "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('@appName', appName)\
            .replace('@edition', edition)
          file.seek(0)
          file.truncate()
          file.write(data)
        with open("./love-android/app/build.gradle", "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('@packageName', packageName)\
            .replace('@versionCode', '${{ inputs.apkCode }}')\
            .replace('@versionName', '${{ inputs.versionName }}')\
            .replace('@storePassword', '${{ inputs.KEY_STORE_PASSWORD }}')\
            .replace('@keyAlias', '${{ inputs.ALIAS }}')\
            .replace('@keyPassword', '${{ inputs.KEY_PASSWORD }}')
          file.seek(0)
          file.truncate()
          file.write(data)
    - name: Build Quatrack
      shell: bash
      run: |
        echo "${{ inputs.SIGNING_KEY }}" | base64 -d > love-android/app/android.keystore
        chmod 777 love-android/gradlew
        cd love-android/
        ./gradlew assembleRelease
    - name: Rename apk
      shell: bash
      run: |
        mv love-android/app/build/outputs/apk/release/app-release.apk ${{ inputs.filePath }}
