name: Quatrack Develop CI

on:
  push:
    branches: [main, ci*]
  pull_request:
    branches: [main]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      appName: ${{ steps.app-info.outputs.appName }}
      versionName: ${{ steps.app-info.outputs.versionName }}
      versionString: ${{ steps.app-info.outputs.versionString }}
      versionCode: ${{ steps.app-info.outputs.versionCode }}
      commitHash: ${{ steps.git-info.outputs.commitHash }}
    steps:
      - uses: actions/checkout@v3
      - name: Install lua
        run: |
          sudo apt-get install lua5.3 -y
      - name: Get app info
        id: app-info
        shell: lua {0}
        run: |
          local version = require 'version'
          print("::set-output name=appName::Quatrack")
          print("::set-output name=versionName::"..version.string)
          print("::set-output name=versionString::"..version.string:sub(2))
          print(("::set-output name=versionCode::%d"):format(version.code))
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          echo "::set-output name=commitHash::$(git rev-parse --short ${{ GITHUB.SHA }})"

  remote-ci:
    runs-on: ubuntu-latest
    needs: get-info
    steps:
      - name: Remote CI
        id: remote-ci
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          owner: 26F-Studio
          repo: 26F-CI
          workflow_file_name: dev.yml
          client_payload: '{
            "repository": "${{ github.repository }}",
            "ref": "${{ github.ref_name }}",
            "appName": "${{ needs.get-info.outputs.appName }}",
            "buildType": "dev",
            "buildList": "./assets/ ./Zenitha/ ./conf.lua ./main.lua ./version.lua",
            "packageName": "Quatrack_${{ needs.get-info.outputs.versionName }}_${{ needs.get-info.outputs.commitHash }}_#${{ GITHUB.RUN_NUMBER }}",
            "versionName": "${{ needs.get-info.outputs.versionName }}",
            "versionString": "${{ needs.get-info.outputs.versionString }}",
            "versionCode": "${{ needs.get-info.outputs.versionCode }}"
            }'
      - name: Get remote CI outputs
        shell: bash
        run: |
          DISPLAY_STRING=$(cat << EOF
          workflow_id: ${{ steps.remote-ci.outputs.workflow_id }}
          workflow_url: ${{ steps.remote-ci.outputs.workflow_url }}
          EOF
          )
          DISPLAY_STRING="${DISPLAY_STRING//'%'/'%25'}"
          DISPLAY_STRING="${DISPLAY_STRING//$'\n'/'%0A'}"
          DISPLAY_STRING="${DISPLAY_STRING//$'\r'/'%0D'}"
          echo "::notice::$DISPLAY_STRING"
      - name: Try download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          repo: 26F-Studio/26F-CI
          workflow: dev.yml
          run_id: ${{ steps.remote-ci.outputs.workflow_id }}
          path: ./artifacts/
      - name: List artifacts
        shell: bash
        run: |
          cd ./artifacts/
          ls -l
