name: Quatrack Develop CI

on:
  push:
    branches: [ main, ci* ]
  pull_request:
    branches: [ main ]

jobs:
  get-info:
    runs-on: ubuntu-20.04
    outputs:
      name: ${{ steps.actual-get-info.outputs.name }}
      apkCode: ${{ steps.actual-get-info.outputs.apkCode }}
      code: ${{ steps.actual-get-info.outputs.code }}
      commit: ${{ steps.actual-get-info.outputs.commit }}
    steps:
    - uses: actions/checkout@v2
    - name: Install lua
      run: |
        sudo apt-get install lua5.3 -y
    - name: Get Version
      id: actual-get-info
      run: |
        echo "::set-output name=name::$(lua .github/workflows/getVersion.lua -name)"
        echo "::set-output name=apkCode::$(lua .github/workflows/getVersion.lua -apkCode)"
        echo "::set-output name=code::$(lua .github/workflows/getVersion.lua -code)"
        echo "::set-output name=commit::$(git rev-parse --short ${{ GITHUB.SHA }})"

  build-love:
    runs-on: ubuntu-20.04
    needs: get-info
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/update-version
      with:
        commit: ${{ needs.get-info.outputs.commit }}
        type: snapshot
    - uses: ./.github/actions/build-love
      with:
        file-path: Quatrack.love
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Quatrack_${{ needs.get-info.outputs.name }}_${{ GITHUB.RUN_NUMBER }}_${{ needs.get-info.outputs.commit }}_Love
        path: Quatrack.love

  build-windows-x64:
    runs-on: windows-latest
    needs: [get-info, build-love]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/update-version
      with:
        commit: ${{ needs.get-info.outputs.commit }}
        type: snapshot
    - uses: ./.github/actions/build-windows
      with:
        love-url: https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
        love-dir: love-11.3-win64
        arch: win64
        version: ${{ needs.get-info.outputs.name }}
        icon: .\.github\build\Windows\icon_snapshot.ico
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Quatrack_${{ needs.get-info.outputs.name }}_${{ GITHUB.RUN_NUMBER }}_${{ needs.get-info.outputs.commit }}_Windows64
        path: love

  build-windows-x86:
    runs-on: windows-latest
    needs: [get-info, build-love]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/update-version
      with:
        commit: ${{ needs.get-info.outputs.commit }}
        type: snapshot
    - uses: ./.github/actions/build-windows
      with:
        love-url: https://github.com/love2d/love/releases/download/11.3/love-11.3-win32.zip
        love-dir: love-11.3-win32
        arch: win32
        version: ${{ needs.get-info.outputs.name }}
        icon: .\.github\build\Windows\icon_snapshot.ico
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Quatrack_${{ needs.get-info.outputs.name }}_${{ GITHUB.RUN_NUMBER }}_${{ needs.get-info.outputs.commit }}_Windows32
        path: love

  build-linux:
    runs-on: ubuntu-20.04
    needs: get-info
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/update-version
      with:
        commit: ${{ needs.get-info.outputs.commit }}
        type: snapshot
    - uses: ./.github/actions/build-linux
      with:
        icon: .github/build/Linux/icon_snapshot.png
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Quatrack_${{ needs.get-info.outputs.name }}_${{ GITHUB.RUN_NUMBER }}_${{ needs.get-info.outputs.commit }}_Linux
        path: Quatrack.AppImage

  build-android:
    runs-on: ubuntu-20.04
    needs: [get-info, build-love]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/update-version
      with:
        commit: ${{ needs.get-info.outputs.commit }}
        type: snapshot
    - uses: ./.github/actions/build-android
      with:
        type: Snapshot
        apkCode: ${{ needs.get-info.outputs.apkCode }}
        name: ${{ needs.get-info.outputs.name }}
        file-path: Quatrack_Snapshot.apk
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        ALIAS: ${{ secrets.ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Quatrack_${{ needs.get-info.outputs.name }}_${{ GITHUB.RUN_NUMBER }}_${{ needs.get-info.outputs.commit }}_Android
        path: Quatrack_Snapshot.apk
